# Generated by Django 2.2.7 on 2019-11-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=9)),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
    ]
