# Generated by Django 2.2.7 on 2019-11-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ipapi', '0001_initial'), ('ipapi', '0002_auto_20191110_0050'), ('ipapi', '0003_auto_20191110_0051')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
    ]
