# Generated by Django 2.2.7 on 2019-11-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipapi', '0001_initial_squashed_0003_auto_20191110_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcoord',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
