version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'ipmap'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/ipmap
    ports:
      - "8000:8000"
    depends_on:
      - db
    user: 1000:1000
    env_file: .env
    environment:
      - IPYTHONDIR=/code/ipmap/.ipython